runtime: python39
entrypoint: gunicorn -b :$PORT main:app --timeout 120 --workers 1 --threads 1

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  PROJECT_ID: ""
  LOCATION: "us-central1"
  ENDPOINT_ID: ""
  GOOGLE_CLOUD_PROJECT: ""

service_account: ""